# Importing the module

In [1]:
import numpy as np

# Checking the version

In [7]:
print(np.__version__)

1.24.3


# Creating an array

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

# Finding the type

In [9]:
print(type(arr))

<class 'numpy.ndarray'>


# 0-D array

In [21]:
zerodim_array = np.array(56)
zerodim_array

array(56)

# 1-D array

In [14]:
onedim_array = np.array([1,2,3])
onedim_array

array([1, 2, 3])

# 2-D array

In [16]:
twodim_array = np.array([[1,2,3],[4,5,6]])
twodim_array

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D array

In [19]:
threedim_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[7,8,9]]])
threedim_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [7, 8, 9]]])

# To find the dimensions of the array

In [25]:
a = np.array(12)
b = np.array([12,5,1996])
c = np.array([[12,5,1996],[7,8,1994]])
d = np.array([[[12,5],[14,7]],[[28,3],[7,8]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher dimensional arrays

In [27]:
highdim = np.array([1,2,3],ndmin=6)
print(highdim)

[[[[[[1 2 3]]]]]]
